site_name: HomelabRC

# Project information
site_url: https://wesleyem.github.io/homelabrc

# Repository
repo_name: wesleyem/homelabrc
repo_url: https://github.com/wesleyem/homelabrc
edit_uri: https://github.com/wesleyem/homelabrc/tree/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - navigation.footer
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wesleyem/homelabrc

plugins:
  - tags
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
