name: Docs
on:
  push:
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
permissions:
  contents: write
jobs:
  pre-commit:
    name: Linting Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Check files
        uses: pre-commit/action@v3.0.1
  test:
    name: Test Build
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get install pngquant
      - run: pip install mike
      - run: pip install mkdocs-material mkdocs-redirects "mkdocs-material[imaging]"
      - name: Test Docs Build
        run: MKINSIDERS=false mkdocs build
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mike
      - run: pip install mkdocs-material
      - name: Sync gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages
          git checkout main
      - name: Docs Deploy for Main
        if: github.ref == 'refs/heads/main'
        run: mike deploy --update --push ${{github.ref_name}}
      - name: Docs Deploy for Tags
        if: github.ref != 'refs/heads/main'
        run: mike deploy --update --push ${{github.ref_name}} latest
